module.exports = {
  siteUrl: 'https://invomaker.com',
  generateRobotsTxt: false,
  sitemapSize: 7000,
  changefreq: 'weekly',
  priority: 0.7,
  exclude: [
    '/admin',
    '/auth',
    '/signup',
    '/statss',
    '/subscription-status',
    '/dashboard',
    '/dashboard/subscription',
    '/dashboard/profile',
    '/dashboard/feedback',
    '/dashboard/my-referrals',
    '/dashboard/invoices',
    '/dashboard/my-invoices',
  ],
};
